npm install @ffmpeg-installer/ffmpeg
npm install @open-wa/wa-automate
npm install @open-wa/wa-decrypt
npm install @vitalets/google-translate-api
npm install acrcloud
npm install axios
npm install chalk
npm install cheerio
npm install correios-brasil
npm install deepai
npm install dotenv
npm install fbdl-core
npm install fluent-ffmpeg
npm install form-data
npm install format-duration-time
npm install fs-extra
npm install g-i-s
npm install genius-lyrics
npm install google-it
npm install imgur
npm install instagram-url-direct
npm install moment-timezone
npm install nedb-async
npm install node-gtts
npm install p-queue
npm install pretty-num
npm install prompt
npm install tiktok-scraper
npm install twitter-url-direct
npm install youtube-sr
npm install ytdl-core